In [196]:
import numpy as np
from sklearn.metrics import accuracy_score


class LinearRegressionUsingGD:
    
    def __init__(self, eta=0.05, n_iterations=1000):
        self.eta = eta
        self.n_iterations = n_iterations

    def fit(self, x, y):
        
        self.cost_ = []
        self.w_ = np.zeros((x.shape[1], 1))
        m = x.shape[0]

        for _ in range(self.n_iterations):
            y_pred = np.dot(x, self.w_)
            residuals = y_pred - y
            gradient_vector = np.dot(x.T, residuals)
            self.w_ -= (self.eta / m) * gradient_vector
            cost = np.sum((residuals ** 2)) / (2 * m)
            self.cost_.append(cost)
        #print(self.cost_)
        return self

    def predict(self, x):
        
        return np.dot(x, self.w_)
    
    def accuracy(self, x, actual_classes, probab_threshold=0):
       
        #predicted_classes = model.predict(x)
        #accuracy = accuracy_score(actual_classes.flatten(),predicted_classes)
        predicted_classes = (self.predict(x) >= probab_threshold).astype(int)
        predicted_classes = predicted_classes.flatten()
        print(predicted_classes)
        accuracy = np.mean(predicted_classes == actual_classes)
        return accuracy * 100

In [197]:
import pandas as pd
import matplotlib.pyplot as plt


import warnings
warnings.filterwarnings('ignore')

import string

In [198]:
def load_data(path, header):
    marks_df = pd.read_csv(path, header=header)
    return marks_df


In [199]:
Train_data = load_data("Gamma_train.txt", None)
X = Train_data.iloc[:, :-1]

# y = target values, last column of the data frame
y = Train_data.iloc[:, -1]

# filter out the applicants that got admitted
C1 = Train_data.loc[y == 1]
C2 = Train_data.loc[y == 2]

In [200]:
X = np.c_[np.ones((X.shape[0], 1)), X]
y = y[:, np.newaxis]
theta = np.zeros((X.shape[1], 1))

In [201]:
print(y)

[[ 1]
 [ 1]
 [ 1]
 ...
 [-1]
 [-1]
 [-1]]


In [202]:
print(X)

[[1.     4.9646 0.5897]
 [1.     1.5701 0.0872]
 [1.     3.3763 0.1963]
 ...
 [1.     7.2153 3.5391]
 [1.     5.2954 5.938 ]
 [1.     3.4157 6.1094]]


In [203]:
model = LinearRegressionUsingGD()

In [212]:
model.fit(X, y)
accuracy = model.accuracy(X, y.flatten())
#parameters = model.w_
y_pred = model.predict(X)

[0 1 1 ... 0 0 0]


In [214]:
for i in range (0,y_pred.shape[0]):
    if y_pred[i] > 0:
        y_pred[i] = 1
    else:
        y_pred[i] = -1
    i = i+1


In [215]:
print(y_pred)

[[-1.]
 [ 1.]
 [ 1.]
 ...
 [-1.]
 [-1.]
 [-1.]]


In [217]:
accuracy = np.mean(y_pred.flatten() == y.flatten())
print(accuracy)

0.9005
