In [21]:
import numpy as np
from sklearn.metrics import accuracy_score


In [22]:
import pandas as pd
import matplotlib.pyplot as plt


import warnings
warnings.filterwarnings('ignore')

import string

In [23]:
# def load_data(path, header):
#     marks_df = pd.read_csv(path, header=header)
#     return marks_df


In [24]:
def read_file(file_path):
        """Read the file and return in a format of numpy array"""
        corpus = pd.read_csv(file_path)
        corpus = np.array(corpus)
        return corpus

In [25]:
file_path1 = "Uniform_train.csv"
file_path2 = "Uniform_test.csv"
Train_data  = read_file(file_path1)
Test_data  = read_file(file_path2)

Train_data1 = Train_data[np.random.randint(Train_data.shape[0], size=20), :]
Train_data2 = Train_data[np.random.randint(Train_data.shape[0], size=100), :]
Train_data3 = Train_data[np.random.randint(Train_data.shape[0], size=200), :]
Train_data4 = Train_data[np.random.randint(Train_data.shape[0], size=1000), :]


In [26]:
X_train1 = Train_data1[:, 0:(Train_data1.shape[1]-1)]
y_train1 = Train_data1[:,(Train_data1.shape[1]-1)]

X_train2 = Train_data2[:, 0:(Train_data1.shape[1]-1)]
y_train2 = Train_data2[:,(Train_data1.shape[1]-1)]

X_train3 = Train_data3[:, 0:(Train_data1.shape[1]-1)]
y_train3 = Train_data3[:,(Train_data1.shape[1]-1)]

X_train4 = Train_data4[:, 0:(Train_data1.shape[1]-1)]
y_train4 = Train_data4[:,(Train_data1.shape[1]-1)]

X_test = Test_data[:, 0:(Train_data1.shape[1]-1)]
y_test = Test_data[:,(Train_data1.shape[1]-1)]

Xt = np.c_[np.ones((X_test.shape[0], 1)), X_test]
yt = y_test[:, np.newaxis]

In [27]:
# Train_data = load_data("Gamma_train.csv", None)
# X = Train_data.iloc[:, :-1]

# # y = target values, last column of the data frame
# y = Train_data.iloc[:, -1]

# # filter out the applicants that got admitted
# C1 = Train_data.loc[y == 1]
# C2 = Train_data.loc[y == -1]

# Train_data1 = Train_data[np.random.randint(Train_data.shape[0], size=10), :]
# Train_data2 = Train_data[np.random.randint(Train_data.shape[0], size=50), :]
# Train_data3 = Train_data[np.random.randint(Train_data.shape[0], size=100), :]
# Train_data4 = Train_data[np.random.randint(Train_data.shape[0], size=500), :]

In [28]:
X = np.c_[np.ones((X_train1.shape[0], 1)), X_train1]
y = y_train1[:, np.newaxis]
theta = np.zeros((X.shape[1], 1))


from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import accuracy_score 
model = LogisticRegression()
model.fit(X, y)
predicted_classes = model.predict(Xt)
accuracy = accuracy_score(yt.flatten(),predicted_classes)
parameters = model.coef_

print(accuracy)
parameters
# rmse = mean_squared_error(y, regression_model.predict(X))
# r2 = r2_score(y, regression_model.predict(X))

# # printing values
# print('Slope:' ,regression_model.coef_)
# print('Intercept:', regression_model.intercept_)
# print('Root mean squared error: ', rmse)
# print('R2 score: ', r2)


0.977977977977978


array([[-0.99567569,  0.55329293,  0.95543305]])

In [29]:
X = np.c_[np.ones((X_train2.shape[0], 1)), X_train2]
y = y_train2[:, np.newaxis]
theta = np.zeros((X.shape[1], 1))

from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import accuracy_score 
model = LogisticRegression()
model.fit(X, y)
predicted_classes = model.predict(Xt)
accuracy = accuracy_score(yt.flatten(),predicted_classes)
parameters = model.coef_

print(accuracy)
parameters

# rmse = mean_squared_error(y, regression_model.predict(X))
# r2 = r2_score(y, regression_model.predict(X))

# # printing values
# print('Slope:' ,regression_model.coef_)
# print('Intercept:', regression_model.intercept_)
# print('Root mean squared error: ', rmse)
# print('R2 score: ', r2)

0.96996996996997


array([[-1.92091265,  1.3582728 ,  1.31413302]])

In [30]:
X = np.c_[np.ones((X_train3.shape[0], 1)), X_train3]
y = y_train3[:, np.newaxis]
theta = np.zeros((X.shape[1], 1))

from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import accuracy_score 
model = LogisticRegression()
model.fit(X, y)
predicted_classes = model.predict(Xt)
accuracy = accuracy_score(yt.flatten(),predicted_classes)
parameters = model.coef_

print(accuracy)
parameters
# rmse = mean_squared_error(y, regression_model.predict(X))
# r2 = r2_score(y, regression_model.predict(X))

# # printing values
# print('Slope:' ,regression_model.coef_)
# print('Intercept:', regression_model.intercept_)
# print('Root mean squared error: ', rmse)
# print('R2 score: ', r2)

0.982982982982983


array([[-2.27862676,  1.83826015,  1.96873071]])

In [31]:
X = np.c_[np.ones((X_train4.shape[0], 1)), X_train4]
y = y_train4[:, np.newaxis]
theta = np.zeros((X.shape[1], 1))

from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import accuracy_score 
model = LogisticRegression()
model.fit(X, y)
predicted_classes = model.predict(Xt)
accuracy = accuracy_score(yt.flatten(),predicted_classes)
parameters = model.coef_

print(accuracy)
parameters
# rmse = mean_squared_error(y, regression_model.predict(X))
# r2 = r2_score(y, regression_model.predict(X))

# # printing values
# print('Slope:' ,regression_model.coef_)
# print('Intercept:', regression_model.intercept_)
# print('Root mean squared error: ', rmse)
# print('R2 score: ', r2)

0.98998998998999


array([[-3.53128362,  3.19112711,  2.97908363]])