In [4]:
import numpy as np
import pandas as pd
import random 
import math
import csv
import matplotlib.pyplot as plt
from scipy.stats import norm
from sys import maxsize

In [5]:
with open('Gamma_test.csv', newline='') as csvfile:
    data = list(csv.reader(csvfile))
at=(np.float_(data))
with open('Gamma_train.csv', newline='') as csvfile:
    data = list(csv.reader(csvfile))
a=(np.float_(data))

xt=at[:,0:2]
yt=at[:,2]
At=np.hstack((xt,np.ones((1000,1))))

N=500
c1=list(range(0,2000))
rds=random.sample(c1,N)

rs=np.sort(rds)
xnew=a[rs,0:2]
A=np.hstack((xnew,np.ones((N,1))))
y=a[rs,2]


In [6]:
A

array([[3.3763, 0.1963, 1.    ],
       [0.1004, 0.0325, 1.    ],
       [0.7315, 0.0163, 1.    ],
       ...,
       [2.5646, 0.2994, 1.    ],
       [2.1993, 0.7786, 1.    ],
       [5.2954, 5.938 , 1.    ]])

In [7]:
l=0

In [8]:
W=np.matmul(np.linalg.inv(np.matmul(A.T,A)),np.matmul(A.T,y))

In [9]:
W

array([-0.17255951, -0.18270296,  0.78470645])

In [10]:
MSE=np.sum(np.square(yt-np.matmul(At,W)))/1000
MSE

0.4149774836415989

In [11]:
WX=np.matmul(At,W.T)
EB=np.matmul(At,W.T)
for i in range(0,1000):
        if WX[i]>0:
            WX[i]=1
        else:
            WX[i]=-1

In [12]:
1000-((WX-yt)==0).sum()

102

In [13]:
epsi=0.0001
eta=0.0001
wk=np.zeros(3)
i=0
wkn=0.1*np.ones(3)

print("Norm",np.dot((wkn-wk),(wkn-wk)))

while np.dot((wkn-wk),(wkn-wk)) > epsi:
    
    sum1=0
    for i in range(0,N):
        ea=np.dot(wk,A[i,:])
        h=1/(1+math.exp(-ea))
        sum1=sum1+h*h*math.exp(-ea)*(A[i,:].T*(h - y[i]))
    wkn = wk
    
    wk=wk-eta*sum1
    print("Norm",np.dot((wkn-wk),(wkn-wk)))

Norm 0.030000000000000006
Norm 0.002281553899196541
Norm 0.0018955084784747147
Norm 0.0014537786972708875
Norm 0.0010942091994928765
Norm 0.0008329224775619021
Norm 0.0006472334382080653
Norm 0.0005139195302827124
Norm 0.0004162655675446525
Norm 0.0003431495203156642
Norm 0.0002872502672700009
Norm 0.00024369329985185853
Norm 0.00020917131388705786
Norm 0.00018139325120736127
Norm 0.0001587392026391017
Norm 0.00014004144972586553
Norm 0.000124443046369264
Norm 0.00011130470697928585
Norm 0.00010014231441100452
Norm 9.058419960878744e-05


In [14]:
yr=[]
for i in range(0,1000):
    if np.dot(wk,At[i,:])>0:
        yr.append(1)
    else:
        yr.append(-1)

In [19]:
wk

array([-0.27868513, -0.29074117, -0.03349415])

In [18]:
for i in range(0,500):
    print(np.dot(wk,A[i,:]))

-1.0314912581670823
-0.0709232236107724
-0.2420914047071016
-0.10508520928005637
-1.6372515573760056
-0.6257922035517084
-0.08438556828887117
-0.05451892357815391
-0.06009790512086667
-0.34650609397665
-0.5138608347062236
-0.10381924733421749
-0.30021221864973785
-0.1588182001201936
-0.054790920133932136
-0.6832446408424394
-0.09267219916960025
-0.03840164585009587
-0.33449369929212064
-0.7841096607439668
-0.8652843829034959
-0.09760257651507338
-0.3214999234659824
-0.07866681184340601
-0.09599394664127388
-0.1512728305404235
-0.04825805083687472
-0.7322631359342268
-0.21577372452877652
-0.1618751577420609
-0.29204453489178406
-0.479139481397244
-0.13458371249287504
-0.1972609092238211
-0.3403697427359905
-0.12094909263721403
-0.1143848400714625
-0.23414984230921942
-0.28879251898156627
-0.20050444833774167
-0.18239078714444462
-0.497582663821064
-0.3246253134064876
-0.36990051800016005
-0.24951513166363387
-0.06732195325048429
-0.04519321249139282
-0.6660013785180808
-0.82203757982628

In [15]:
1000 - ((yr-yt)==0).sum()

500