In [194]:
import numpy as np
import pandas as pd
import random 
import math
import matplotlib.pyplot as plt
from scipy.stats import norm
from sys import maxsize

In [195]:
a=np.loadtxt(open("german.data-numeric", "rb"))

for i in range(0,1000):
    if a[i,24]==2:
        a[i,24]=-1


c1=list(range(0,1000))
rds=random.sample(c1,700)
rds_sort=np.sort(rds)
x=a[rds_sort,0:24]
y=a[rds_sort,24]
np.ones(700).shape
xnew=np.hstack((x,np.ones((700,1))))


In [196]:
xnew

array([[ 2., 48.,  2., ...,  0.,  1.,  1.],
       [ 4., 12.,  4., ...,  1.,  0.,  1.],
       [ 1., 42.,  2., ...,  0.,  1.,  1.],
       ...,
       [ 4., 12.,  2., ...,  1.,  0.,  1.],
       [ 1., 30.,  2., ...,  0.,  0.,  1.],
       [ 4., 12.,  2., ...,  0.,  1.,  1.]])

# Linear Least Squares
    

In [197]:
A = xnew
w_star= np.matmul(np.linalg.inv(np.matmul(A.T,A)),np.matmul(A.T,y))

In [198]:
w_star

array([ 1.79618955e-01, -1.42903235e-02,  1.39529540e-01, -6.28861581e-04,
        2.88069614e-02,  4.52969183e-02,  8.87101952e-02, -1.55399800e-02,
       -2.55188472e-02,  1.32017706e-03,  5.16084864e-02, -1.66732280e-01,
        2.49112886e-02,  1.66339818e-01,  3.54357813e-01, -2.40651361e-01,
        2.36427698e-01, -2.54015441e-01, -2.70776302e-01, -5.66088422e-02,
        8.20843961e-02,  3.97480448e-01,  6.68692130e-02,  3.40594650e-02,
       -8.40216257e-01])

In [199]:
cost=np.dot((y-np.matmul(A,w_star.T)),(y-np.matmul(A,w_star.T)))/700
cost

0.6523205106689091

In [200]:
yr=[]
for i in range(0,700):
    if np.dot(w_star,xnew[i,:])>0:
        yr.append(1)
    else:
        yr.append(-1)

In [201]:
costr=np.dot((y-yr),(y-yr))/700
costr

0.9371428571428572

### Test

In [202]:
rds_rem=np.setdiff1d(range(0,1000),rds_sort)
xt=a[rds_rem,0:24]
yt=a[rds_rem,24]
np.ones(700).shape
xnewt=np.hstack((xt,np.ones((300,1))))




In [203]:
xnewt.shape

(300, 25)

In [204]:
y1=[]
for i in range(0,300):
    if np.dot(w_star,xnewt[i,:])>0:
        y1.append(1)
    else:
        y1.append(-1)

In [205]:
At=xnewt
costt=np.dot((yt-np.matmul(At,w_star.T)),(yt-np.matmul(At,w_star.T)))/300
costt

0.5990942769808714

In [206]:
cost1=np.dot((yt-y1),(yt-y1))/4
cost1

62.0

***


# Logistic Regression

In [207]:
epsi=0.0001
eta=0.0001
wk=np.zeros(25)
i=0
wkn=0.1*np.ones(25)

print("Norm",np.dot((wkn-wk),(wkn-wk)))

while np.dot((wkn-wk),(wkn-wk)) > epsi:
    
    sum1=0
    for i in range(0,700):
        ea=np.dot(wk,xnew[i,:])
        h=1/(1+math.exp(-ea))
        sum1=sum1+h*h*math.exp(-ea)*(xnew[i,:].T*(h - y[i]))
    wkn = wk
    
    wk=wk-eta*sum1
    print("Norm",np.dot((wkn-wk),(wkn-wk)))


Norm 0.25
Norm 0.020811274375
Norm 9.356892177187573e-05


In [208]:
(np.dot(xnew,wk))

array([-10.97271001,  -5.26372929, -13.56942037,  -9.36157789,
       -13.9970807 ,  -7.08368683, -11.61881802,  -6.84433753,
        -9.04843757,  -5.67319681,  -6.655744  , -17.25697854,
        -5.01806268,  -5.15491689,  -4.73794018,  -4.14867023,
        -3.51279361,  -2.58726056,  -4.57986988, -14.49058618,
        -4.9388971 ,  -4.76316322,  -3.92559996,  -9.48472809,
        -5.18967189,  -2.26608436,  -6.00622526,  -3.32296929,
        -9.97808417, -12.63236613,  -4.36463075,  -9.78269161,
        -3.39088096,  -6.33921817,  -7.50703872,  -2.43942254,
       -10.12874351,  -4.89682456,  -7.46181405,  -6.3635653 ,
        -9.68689819,  -4.5166506 ,  -6.21962123,  -6.35295033,
        -4.1135672 , -11.3260896 ,  -6.57885896,  -8.19527168,
        -7.27886445, -10.02348667,  -4.1157432 ,  -6.21812189,
        -5.47237499,  -3.65606258,  -3.91060981,  -5.03330708,
        -3.30989308,  -4.73210881,  -3.18899475,  -6.56720151,
        -4.62905031,  -5.66543249,  -5.62791225,  -6.71

In [209]:
yr=[]
for i in range(0,300):
    if np.dot(wk,xnewt[i,:])>0:
        yr.append(1)
    else:
        yr.append(-1)

In [210]:
costrr=np.dot((yt-yr),(yt-yr))
costrr

836.0

# From Scikit-Learn

In [211]:
a=np.loadtxt(open("german.data-numeric", "rb"))

for i in range(0,1000):
    if a[i,24]==2:
        a[i,24]=0



x=a[rds_sort,0:24]
y=a[rds_sort,24]
np.ones(700).shape
xnew=np.hstack((x,np.ones((700,1))))

A=xnew

rds_rem=np.setdiff1d(range(0,1000),rds_sort)
xt=a[rds_rem,0:24]
yt=a[rds_rem,24]
np.ones(700).shape
xnewt=np.hstack((xt,np.ones((300,1))))
At=xnewt

In [212]:
A=xnew
At=xnewt

In [213]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score 
model = LogisticRegression()
model.fit(A, y)
predicted_classes = model.predict(A)
accuracy = accuracy_score(y.flatten(),predicted_classes)
parameters = model.coef_

C:\Users\range\.julia\conda\3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [214]:
parameters

array([[ 0.50580472, -0.0381684 ,  0.38890611, -0.00274013,  0.10310249,
         0.11974022,  0.21349138, -0.05960118, -0.10906901,  0.00392915,
         0.13773397, -0.46030471,  0.04250914,  0.39421072,  0.66926972,
        -0.61303955,  0.70294453, -0.64785843, -0.55427491, -0.2708434 ,
         0.11568048,  0.68530403,  0.00722078, -0.01752441, -0.80140666]])

In [215]:
accuracy

0.7685714285714286

In [216]:
yr=[]

for i in range(0,300):
    if 1/(1+math.exp(-np.dot(parameters,At[i,:])))>0.5:
        yr.append(1)
    else:
        yr.append(0)
300 - ((yr-yt)==0).sum()

77

# LMS

In [217]:
wk=np.zeros(25)
i=0
wk1=0.1*np.ones(25)
print("Norm",np.dot((wk1-wk),(wk1-wk)))

Norm 0.25


In [218]:
xnew.shape

(700, 25)

In [219]:
epsi=0.0001
eta=0.000001
wk=np.zeros(25)
i=0
wkn=0.1*np.ones(25)

print("Norm",np.dot((wkn-wk),(wkn-wk)))

while np.dot((wkn-wk),(wkn-wk)) > epsi:
    
    
    print("Norm",np.dot((wkn-wk),(wkn-wk)))
    grad_f= np.matmul(xnew.T,(np.dot(xnew,wk)-y))
    wkn=wk
    wk=wk-eta*grad_f
    #print(grad_f)
    i=i+1

Norm 0.25
Norm 0.25
Norm 0.0006247991379999999
Norm 0.0009965174743387362
Norm 0.0016061351770336554
Norm 0.0025977043172176664
Norm 0.004206253683543918
Norm 0.0068134324837598546
Norm 0.011038027464047596
Norm 0.01788280741302834
Norm 0.028972535223959907
Norm 0.0469396368535142
Norm 0.07604907107354705
Norm 0.1232107268011254
Norm 0.19961966588614638
Norm 0.32341356555415446
Norm 0.523978174213968
Norm 0.8489227939727311
Norm 1.3753816045845193
Norm 2.228323496213799
Norm 3.610216732914922
Norm 5.849090137421841
Norm 9.476399387593606
Norm 15.35318204455496
Norm 24.874447537189063
Norm 40.30031945884038
Norm 65.29253553787922
Norm 105.78365770624438
Norm 171.38532221073308
Norm 277.66981508907963
Norm 449.86656515178356
Norm 728.85101461469
Norm 1180.8474838494722
Norm 1913.1492612206014
Norm 3099.5874961223394
Norm 5021.794609000986
Norm 8136.057177508666
Norm 13181.62759529935
Norm 21356.20513359676
Norm 34600.241465745516
Norm 56057.558072691114
Norm 90821.61522444306
Norm 147144

Norm 4.477428646551161e+116
Norm 7.254103027552357e+116
Norm 1.1752730169106671e+117
Norm 1.904117792416248e+117
Norm 3.084955168056678e+117
Norm 4.9980880525479373e+117
Norm 8.097649016001347e+117
Norm 1.3119400638194075e+118
Norm 2.1255388170731067e+118
Norm 3.4436902930852536e+118
Norm 5.579292525468716e+118
Norm 9.039287054139412e+118
Norm 1.4644994875988873e+119
Norm 2.3727078654895054e+119
Norm 3.8441410615895644e+119
Norm 6.228082570270512e+119
Norm 1.0090423811364504e+120
Norm 1.6347993390288236e+120
Norm 2.6486190559003616e+120
Norm 4.291158392225675e+120
Norm 6.952317399570032e+120
Norm 1.1263792385741957e+121
Norm 1.8249025701407853e+121
Norm 2.9566146786600906e+121
Norm 4.790157294476237e+121
Norm 7.76077013735947e+121
Norm 1.2573606548240938e+122
Norm 2.0371120240878297e+122
Norm 3.3004256835631476e+122
Norm 5.347182464155751e+122
Norm 8.663234093520437e+122
Norm 1.4035732923317132e+123
Norm 2.273998330970113e+123
Norm 3.684216875247262e+123
Norm 5.968981506712942e+123
Nor

Norm 2.826917138250799e+182
Norm 4.580027911113791e+182
Norm 7.420329157423059e+182
Norm 1.2022041322257527e+183
Norm 1.9477502208845405e+183
Norm 3.155646217861592e+183
Norm 5.112618109616671e+183
Norm 8.283204811372424e+183
Norm 1.3420028735979175e+184
Norm 2.17424505823208e+184
Norm 3.522601677128001e+184
Norm 5.707140751555749e+184
Norm 9.246420272139318e+184
Norm 1.4980581620616762e+185
Norm 2.4270779294789497e+185
Norm 3.9322286844035747e+185
Norm 6.370797673466448e+185
Norm 1.0321643590370595e+186
Norm 1.6722603960623088e+186
Norm 2.7093115624021124e+186
Norm 4.389489316048043e+186
Norm 7.111628180044744e+186
Norm 1.1521899640193354e+187
Norm 1.8667197997105143e+187
Norm 3.0243648351833627e+187
Norm 4.899922665261357e+187
Norm 7.938606429434405e+187
Norm 1.2861727897923018e+188
Norm 2.08379198528925e+188
Norm 3.3760541914876864e+188
Norm 5.4697119406952044e+188
Norm 8.86175014299761e+188
Norm 1.435735856812541e+189
Norm 2.3261064883058936e+189
Norm 3.768639871508929e+189
Norm 6.

Norm 8.537243489077821e+271
Norm 1.383160932978218e+272
Norm 2.2409272606137508e+272
Norm 3.630636802724774e+272
Norm 5.882173788045839e+272
Norm 9.529999929160202e+272
Norm 1.544002301230304e+273
Norm 2.5015142958291196e+273
Norm 4.0528267135685236e+273
Norm 6.56618448977142e+273
Norm 1.0638199410147514e+274
Norm 1.7235471660346656e+274
Norm 2.7924037884762074e+274
Norm 4.524111130556343e+274
Norm 7.329735622795723e+274
Norm 1.1875266267712982e+275
Norm 1.923970470237683e+275
Norm 3.117119470753142e+275
Norm 5.050199026052621e+275
Norm 8.182076574877177e+275
Norm 1.3256185891248143e+276
Norm 2.147700070699523e+276
Norm 3.4795948333283614e+276
Norm 5.637463242333409e+276
Norm 9.133532302167668e+276
Norm 1.4797686251557918e+277
Norm 2.3974461484915054e+277
Norm 3.8842207742522096e+277
Norm 6.2930176899386935e+277
Norm 1.0195628402071332e+278
Norm 1.651844053756924e+278
Norm 2.6762340390689102e+278
Norm 4.335898788739438e+278
Norm 7.024803523062901e+278
Norm 1.1381230730245824e+279
Norm 

Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
N

Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf
Norm inf


C:\Users\range\.julia\conda\3\lib\site-packages\ipykernel_launcher.py:15: RuntimeWarning: invalid value encountered in subtract
  from ipykernel import kernelapp as app


In [220]:
epsi=0.01
eta=0.00001
wk=np.zeros(25)
i=0
wkn=0.1*np.ones(25)

print("Norm",np.dot((wkn-wk),(wkn-wk)))

while np.dot((wkn-wk),(wkn-wk)) > epsi:
    
    '''
    print("Norm",np.dot((wkn-wk),(wkn-wk)))
    grad_f= np.matmul(xnew.T,(np.dot(xnew,wk)-y))
    wkn=wk
    wk=wk-eta*grad_f
    #print(grad_f)
    i=i+1
    '''
    sum1=0
    for i in range(0,700):
        sum1=sum1+(xnew[i,:].T*(np.dot(xnew[i,:],wk) - y[i]))
    wkn = wk
    
    wk=wk-eta*sum1
    print("Norm",np.dot((wkn-wk),(wkn-wk)))
    #print(wk)
    

Norm 0.25
Norm 0.06247991380000001
Norm 28.818229458112427
Norm 13603.871604763306
Norm 6422763.839339592
Norm 3032367201.2963915
Norm 1431665732763.6929
Norm 675929606932643.5
Norm 3.191253538256204e+17
Norm 1.5066804355039314e+20
Norm 7.113461552073221e+22
Norm 3.3584650109231435e+25
Norm 1.5856256686040054e+28
Norm 7.486184172705783e+30
Norm 3.534437829643054e+33
Norm 1.668707379275809e+36
Norm 7.878436265862281e+38
Norm 3.719631060910818e+41
Norm 1.7561423057064302e+44
Norm 8.291241113404172e+46
Norm 3.9145278248365147e+49
Norm 1.8481585424703502e+52
Norm 8.72567561388782e+54
Norm 4.11963655547792e+57
Norm 1.944996135567797e+60
Norm 9.182873091907486e+62
Norm 4.3354923272103e+65
Norm 2.0469077086412092e+68
Norm 9.664026254639392e+70
Norm 4.562658250593854e+73
Norm 2.1541591220034374e+76
Norm 1.017039030329885e+79
Norm 4.801726941380057e+81
Norm 2.2670301661969147e+84
Norm 1.0703286207627832e+87
Norm 5.0533220664892383e+89
Norm 2.3858152918931047e+92
Norm 1.1264104151955497e+95
Norm

C:\Users\range\.julia\conda\3\lib\site-packages\ipykernel_launcher.py:21: RuntimeWarning: overflow encountered in add
C:\Users\range\.julia\conda\3\lib\site-packages\ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in multiply
C:\Users\range\.julia\conda\3\lib\site-packages\ipykernel_launcher.py:24: RuntimeWarning: invalid value encountered in subtract


In [221]:
xnew.shape


(700, 25)

In [222]:
wk

array([-inf,  nan,  nan,  nan, -inf, -inf, -inf, -inf, -inf,  nan, -inf,
       -inf, -inf, -inf, -inf,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan, -inf])

In [223]:
y.shape

(700,)