In [86]:
import numpy as np
import pandas as pd
import random 
import math
import matplotlib.pyplot as plt
from scipy.stats import norm
from sys import maxsize

In [87]:
a=np.loadtxt(open("german.data-numeric", "rb"))

for i in range(0,1000):
    if a[i,24]==2:
        a[i,24]=-1

a
c1=list(range(0,1000))
rds=random.sample(c1,700)
rds_sort=np.sort(rds)
x=a[rds_sort,0:24]
y=a[rds_sort,24]



# Linear Least Squares
    

In [88]:
A = x
w_star= np.matmul(np.linalg.inv(np.matmul(A.T,A)),np.matmul(A.T,y))

In [89]:
w_star

array([ 1.77168849e-01, -1.66239802e-02,  1.77460796e-01,  8.87965167e-05,
        5.00416029e-02,  2.62911202e-02,  5.26214898e-02, -5.67688972e-03,
       -6.56144851e-02,  1.09352030e-03,  8.88120800e-02, -1.50131848e-01,
       -3.90296717e-02,  5.20092318e-02,  1.27511193e-01, -3.31206439e-01,
        2.19971745e-01, -4.02240080e-01, -5.50235604e-01, -3.18916081e-01,
       -9.50666882e-02,  2.38923285e-01,  3.08903431e-02, -7.31012513e-03])

In [90]:
cost=np.dot((y-np.matmul(A,w_star.T)),(y-np.matmul(A,w_star.T)))/700
cost

0.6099884743653771

In [91]:
yr=[]
for i in range(0,700):
    if np.dot(w_star,x[i,0:24])>0:
        yr.append(1)
    else:
        yr.append(-1)

In [92]:
costr=np.dot((y-yr),(y-yr))/700
costr

0.8114285714285714

### Test

In [93]:
rds_rem=np.setdiff1d(range(0,1000),rds_sort)
xt=a[rds_rem,0:24]
yt=a[rds_rem,24]

In [94]:
xt[1:3,2:24]

array([[ 4., 21.,  1.,  4.,  3.,  3.,  1., 49.,  3.,  1.,  2.,  1.,  1.,
         0.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,  0.],
       [ 2., 79.,  1.,  4.,  3.,  4.,  2., 45.,  3.,  1.,  2.,  1.,  1.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [95]:
y1=[]
for i in range(0,300):
    if np.dot(w_star,xt[i,0:24])>0:
        y1.append(1)
    else:
        y1.append(-1)

In [96]:
At=xt
costt=np.dot((yt-np.matmul(At,w_star.T)),(yt-np.matmul(At,w_star.T)))/300
costt

0.7021324594315351

In [97]:
cost1=np.dot((yt-y1),(yt-y1))/300
cost1

1.1066666666666667

***


# Logistic Regression

# LMS

In [98]:
epsi=0.1
eta=0.00001
wk=np.zeros(24)
i=0
wk1=0.1*np.ones(24)

while np.linalg.norm(wk1-wk)>epsi:
    wk=wk1
    grad_f= np.matmul(x.T,(np.dot(x,wk)-y))
    wk1=wk-eta*grad_f
    print(grad_f)
    i=i+1


    
    
    
    

[2.042110e+04 1.967377e+05 2.030070e+04 3.342617e+05 1.736870e+04
 2.746990e+04 2.143760e+04 2.310370e+04 2.024760e+04 2.957158e+05
 2.116280e+04 1.137950e+04 9.238100e+03 1.170690e+04 8.253900e+03
 1.768500e+03 1.033800e+03 7.264200e+03 3.869000e+02 1.385800e+03
 5.346000e+03 1.603000e+02 1.394100e+03 4.977600e+03]
[-4.47585001e+05 -4.37207863e+06 -4.42707841e+05 -7.74299293e+06
 -3.80236440e+05 -5.97254686e+05 -4.66298071e+05 -5.01994742e+05
 -4.44323084e+05 -6.50241880e+06 -4.60985564e+05 -2.47364900e+05
 -2.01129108e+05 -2.57392282e+05 -1.79762170e+05 -3.71900040e+04
 -2.42701232e+04 -1.57993578e+05 -8.52548614e+03 -2.91926274e+04
 -1.16291533e+05 -3.42180866e+03 -2.97219077e+04 -1.06959987e+05]
[1.00855236e+07 9.87712998e+07 9.97617708e+06 1.75194084e+08
 8.57257078e+06 1.34604711e+07 1.05123867e+07 1.13141206e+07
 1.00254821e+07 1.46387971e+08 1.03924006e+07 5.57593479e+06
 4.53399843e+06 5.80459161e+06 4.05241139e+06 8.38344604e+05
 5.48520011e+05 3.56167073e+06 1.93011033e+05 6

C:\Users\range\.julia\conda\3\lib\site-packages\ipykernel_launcher.py:10: RuntimeWarning: invalid value encountered in subtract
  # Remove the CWD from sys.path while we load stuff.


In [47]:
x.T.shape


(24, 700)

In [42]:
wk1

array([inf, nan, nan, nan, inf, inf, inf, inf, inf, nan, inf, inf, inf,
       inf, inf, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [17]:
y.shape

(700,)