In [18]:
import numpy as np
import pandas as pd
import random 
import math
import csv
import scipy
import matplotlib.pyplot as plt
from scipy.stats import norm
from sys import maxsize

In [34]:
with open('Uniform_test.csv', newline='') as csvfile:
    data = list(csv.reader(csvfile))
at=(np.float_(data))
with open('Uniform_train.csv', newline='') as csvfile:
    data = list(csv.reader(csvfile))
a=(np.float_(data))

xt=at[:,0:2]
yt=at[:,2]
At=np.hstack((xt,np.ones((1000,1))))

N=500
c1=list(range(0,1000))
c2=list(range(1000,2000))
rds1=random.sample(c1,N)
rds2=random.sample(c2,N)

rs1=np.sort(rds1)
rs2=np.sort(rds2)

#A=np.vstack((a[rs1,0:2],a[rs2,0:2]))
A=np.hstack((xnew,np.ones((2*N,1))))
y=np.concatenate((a[rs1,2],a[rs2,2]))

In [35]:
A

array([[1.1772, 2.4442, 1.    ],
       [0.5667, 4.2812, 1.    ],
       [1.6254, 1.5892, 1.    ],
       ...,
       [0.6069, 0.1454, 1.    ],
       [0.0992, 0.1162, 1.    ],
       [0.6247, 0.4368, 1.    ]])

In [36]:
y0=y
y0t=yt

for i in range(0,2*N):
    if y[i]==-1:
        y0[i]=0
        
for i in range(0,1000):
    if yt[i]==-1:
        y0t[i]=0

In [37]:
def logistic_loss(y,y_hat):
    return -np.mean(y*np.log(y_hat)+(1-y)*np.log(1-y_hat))

In [38]:
def sigmoid(Z):
    return 1/(1+np.e**(-Z))

In [39]:
W=np.zeros((2,1))
b=np.zeros((1,1))
l=0.01


In [40]:
m=len(y0)

for epoch in range(5000):
    Z=np.matmul(A,W)+b
    A1=sigmoid(Z)
    loss=logistic_loss(y0,A1)
    dz=A1-y0
    dw=1/m*np.matmul(A.T,dz)
    db=np.sum(dz)
    
    W=W-l*dw
    b=b-l*db
    
    if epoch%100==0:
        print(loss)

ValueError: shapes (1000,3) and (2,1) not aligned: 3 (dim 1) != 2 (dim 0)

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score 
model = LogisticRegression()
model.fit(A, y0)
predicted_classes = model.predict(A)
accuracy = accuracy_score(y0.flatten(),predicted_classes)
parameters = model.coef_

C:\Users\range\.julia\conda\3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [27]:
parameters

array([[2.65772929, 2.82653792]])

In [28]:
from sklearn.linear_model import LogisticRegression

In [41]:
# instantiate a logistic regression model, and fit with X and y
model = LogisticRegression()
model = model.fit(A, y0)

# check the accuracy on the training set
model.score(A, y0)

C:\Users\range\.julia\conda\3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.984

In [42]:
model.coef_

array([[ 3.103214  ,  3.12082443, -3.47640284]])